In [3]:
import sqlite3
import pandas as pd

# Parse the database



db_name = "panda_v1.db"
sql_query = "Select * from Task"

conn = sqlite3.connect('C:\\Users\\Varun\\Documents\\Misc\\Research\\MalSami\\' + db_name)

cursor = conn.cursor()
print("Opened database file")

df = pd.read_sql_query(sql_query, conn)

cursor.close()
df

Opened database file

,Task_ID,Priority,Deadline,Quota,CAPS,PKG,Arg,CORES,COREOFFSET,CRITICALTIME,Period,Number_of_Jobs,OFFSET
0,0,2,0,100M,235,pi,524288,2,1,7500,8000,2,0
1,1,5,0,100M,235,hey,1,2,1,2500,3000,4,0
2,2,3,0,100M,235,hey,1,2,1,7500,8000,2,0
3,3,5,0,100M,235,pi,32768,2,1,4500,5000,6,0
4,4,2,0,100M,235,pi,262144,2,1,3500,4000,5,0
5,5,5,0,100M,235,tumatmul,262144,2,1,3500,4000,8,0
6,6,2,0,100M,235,tumatmul,262144,2,1,1500,2000,8,0
7,7,1,0,100M,235,pi,16384,2,1,1500,2000,1,0
8,8,4,0,100M,235,pi,65536,2,1,5500,6000,7,0
9,9,3,0,100M,235,tumatmul,524288,2,1,6500,7000,2,0
10,10,5,0,100M,235,hey,1,2,1,1500,2000,8,0
11,11,5,0,100M,235,pi,8192,2,1,5500,6000,6,0
12,12,5,0,100M,235,hey,1,2,1,2500,3000,2,0
13,13,3,0,100M,235,cond_mod,7625597484987,2,1,7500,8000,5,0
14,14,3,0,100M,235,pi,131072,2,1,3500,4000,8,0
15,15,1,0,100M,235,hey,1,2,1,4500,5000,3,0
16,16,1,0,100M,235,cond_mod,7625597484987,2,1,7500,8000,8,0
17,17,5,0,100M,235,pi,524288,2,1,3500,4000,5,0
18,18,4,0,100M,235,pi,524288,2,1,4500,5000,2,0
19,19,5,0,100M,235,tumatmul,4096,2,1,500,1000,8,0
20,20,3,0,100M,235,hey,1,2,1,5500,6000,7,0
21,21,3,0,100M,235,cond_mod,847288609443,2,1,4500,5000,1,0
22,22,3,0,100M,235,cond_mod,68630377364883,2,1,5500,6000,8,0
23,23,5,0,100M,235,pi,32768,2,1,3500,4000,1,0
24,24,2,0,100M,235,tumatmul,4096,2,1,500,1000,6,0
25,25,4,0,100M,235,pi,131072,2,1,4500,5000,2,0
26,26,2,0,100M,235,pi,262144,2,1,3500,4000,6,0
27,27,3,0,100M,235,hey,1,2,1,2500,3000,4,0
28,28,5,0,100M,235,hey,1,2,1,7500,8000,4,0
29,29,5,0,100M,235,hey,1,2,1,5500,6000,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
353,353,5,0,100M,235,cond_mod,22876792454961,2,1,2500,3000,6,0
354,354,2,0,100M,235,cond_mod,205891132094649,2,1,6500,7000,4,0
355,355,4,0,100M,235,cond_mod,7625597484987,2,1,2500,3000,4,0
356,356,5,0,100M,235,cond_mod,7625597484987,2,1,2500,3000,6,0
357,357,3,0,100M,235,cond_mod,68630377364883,2,1,500,1000,1,0
358,358,2,0,100M,235,cond_mod,2541865828329,2,1,5500,6000,2,0
359,359,3,0,100M,235,tumatmul,524288,2,1,1500,2000,1,0
360,360,3,0,100M,235,cond_mod,847288609443,2,1,2500,3000,1,0
361,361,3,0,100M,235,cond_mod,2541865828329,2,1,3500,4000,7,0
362,362,3,0,100M,235,cond_mod,2541865828329,2,1,6500,7000,2,0
363,363,5,0,100M,235,cond_mod,2541865828329,2,1,6500,7000,4,0
364,364,5,0,100M,235,cond_mod,847288609443,2,1,500,1000,4,0
365,365,1,0,100M,235,cond_mod,205891132094649,2,1,3500,4000,1,0
366,366,3,0,100M,235,cond_mod,22876792454961,2,1,2500,3000,3,0
367,367,2,0,100M,235,cond_mod,205891132094649,2,1,3500,4000,8,0
368,368,4,0,100M,235,cond_mod,22876792454961,2,1,1500,2000,8,0
369,369,1,0,100M,235,cond_mod,847288609443,2,1,2500,3000,4,0
370,370,4,0,100M,235,cond_mod,68630377364883,2,1,2500,3000,3,0
371,371,5,0,100M,235,cond_mod,2541865828329,2,1,4500,5000,2,0
372,372,2,0,100M,235,cond_mod,2541865828329,2,1,3500,4000,6,0
373,373,1,0,100M,235,cond_mod,847288609443,2,1,500,1000,7,0
374,374,1,0,100M,235,cond_mod,205891132094649,2,1,500,1000,3,0
375,375,1,0,100M,235,cond_mod,68630377364883,2,1,500,1000,1,0
376,376,1,0,100M,235,pi,524288,2,1,500,1000,4,0
377,377,2,0,100M,235,cond_mod,205891132094649,2,1,7500,8000,3,0
378,378,1,0,100M,235,cond_mod,7625597484987,2,1,5500,6000,8,0
379,379,3,0,100M,235,tumatmul,131072,2,1,500,1000,7,0
380,380,1,0,100M,235,cond_mod,22876792454961,2,1,500,1000,2,0
381,381,1,0,100M,235,pi,2097152,2,1,500,1000,4,0
382,382,2,0,100M,235,cond_mod,7625597484987,2,1,3500,4000,3,0

In [4]:
"""Dataset """
"""DO NOT SHUFFLE OR FUCK WITH ORDER OF DATA """

one_tskst_sql_query = ( 'select TaskSet.Set_ID, Task.*, TaskSet.Successful '
                        'from Task '
                        'inner join TaskSet on Task.Task_ID = TaskSet.TASK1_ID '
                      )

two_tskst_sql_query = ( 'select TaskSet.Set_ID, t1.*, t2.*, TaskSet.Successful '
                        'from Task t1, Task t2 '
                        'inner join TaskSet on t1.Task_ID = TaskSet.TASK1_ID ' 
                        'and '
                        't2.Task_ID = TaskSet.TASK2_ID '
                        'and '
                        'TaskSet.TASK3_ID = -1 and TaskSet.TASK4_ID = -1 '
                     )


three_tskst_sql_query = ('select TaskSet.Set_ID, t1.*, t2.*, t3.*, TaskSet.Successful '
                         'from Task t1, Task t2, Task t3 '
                         'inner join TaskSet on t1.Task_ID = TaskSet.TASK1_ID '
                         'and '
                         't2.Task_ID = TaskSet.TASK2_ID '
                         'and ' 
                         't3.Task_ID = TaskSet.TASK3_ID '
                         'and TaskSet.TASK4_ID = -1 '

                        )


sql_query = two_tskst_sql_query

conn = sqlite3.connect('C:\\Users\\Varun\\Documents\\Misc\\Research\\MalSami\\' + db_name)
cursor = conn.cursor()

tkst_df = pd.read_sql_query(sql_query, conn)

tkst_df

,Set_ID,Task_ID,Priority,Deadline,Quota,CAPS,PKG,Arg,CORES,COREOFFSET,...,CAPS,PKG,Arg,CORES,COREOFFSET,CRITICALTIME,Period,Number_of_Jobs,OFFSET,Successful
0,327,37,2,0,100M,235,pi,524288,2,1,...,235,pi,131072,2,1,2500,3000,7,0,1
1,328,113,2,0,100M,235,pi,2097152,2,1,...,235,hey,1,2,1,3500,4000,7,0,1
2,329,62,3,0,100M,235,hey,1,2,1,...,235,cond_mod,22876792454961,2,1,6500,7000,4,0,1
3,330,165,1,0,100M,235,pi,131072,2,1,...,235,tumatmul,524288,2,1,4500,5000,5,0,1
4,331,145,1,0,100M,235,tumatmul,32768,2,1,...,235,pi,262144,2,1,5500,6000,3,0,1
5,332,40,3,0,100M,235,tumatmul,262144,2,1,...,235,tumatmul,32768,2,1,2500,3000,2,0,1
6,333,70,1,0,100M,235,pi,8192,2,1,...,235,tumatmul,262144,2,1,6500,7000,4,0,1
7,334,101,4,0,100M,235,cond_mod,68630377364883,2,1,...,235,hey,1,2,1,7500,8000,7,0,1
8,335,36,2,0,100M,235,hey,1,2,1,...,235,pi,8192,2,1,4500,5000,3,0,1
9,336,51,4,0,100M,235,tumatmul,4096,2,1,...,235,tumatmul,4096,2,1,5500,6000,3,0,1
10,337,92,2,0,100M,235,hey,1,2,1,...,235,pi,8192,2,1,3500,4000,8,0,1
11,338,247,2,0,100M,235,hey,1,2,1,...,235,hey,1,2,1,500,1000,1,0,1
12,339,128,3,0,100M,235,hey,1,2,1,...,235,tumatmul,8192,2,1,5500,6000,5,0,1
13,340,216,3,0,100M,235,hey,1,2,1,...,235,tumatmul,65536,2,1,2500,3000,6,0,1
14,341,62,3,0,100M,235,hey,1,2,1,...,235,hey,1,2,1,7500,8000,3,0,1
15,342,237,1,0,100M,235,hey,1,2,1,...,235,hey,1,2,1,5500,6000,8,0,1
16,343,150,1,0,100M,235,tumatmul,16384,2,1,...,235,tumatmul,131072,2,1,2500,3000,7,0,1
17,344,122,2,0,100M,235,tumatmul,262144,2,1,...,235,hey,1,2,1,2500,3000,7,0,1
18,345,102,4,0,100M,235,pi,262144,2,1,...,235,pi,16384,2,1,3500,4000,7,0,1
19,346,50,5,0,100M,235,hey,1,2,1,...,235,pi,16384,2,1,500,1000,5,0,1
20,347,99,2,0,100M,235,cond_mod,847288609443,2,1,...,235,hey,1,2,1,7500,8000,1,0,1
21,348,224,4,0,100M,235,hey,1,2,1,...,235,pi,131072,2,1,500,1000,2,0,1
22,349,108,3,0,100M,235,hey,1,2,1,...,235,hey,1,2,1,1500,2000,2,0,1
23,350,26,2,0,100M,235,pi,262144,2,1,...,235,cond_mod,847288609443,2,1,6500,7000,3,0,1
24,351,51,4,0,100M,235,tumatmul,4096,2,1,...,235,tumatmul,65536,2,1,7500,8000,2,0,1
25,352,71,1,0,100M,235,pi,524288,2,1,...,235,tumatmul,4096,2,1,6500,7000,7,0,1
26,353,84,1,0,100M,235,hey,1,2,1,...,235,tumatmul,131072,2,1,2500,3000,7,0,1
27,354,22,3,0,100M,235,cond_mod,68630377364883,2,1,...,235,pi,16384,2,1,5500,6000,1,0,1
28,355,97,3,0,100M,235,pi,2097152,2,1,...,235,pi,16384,2,1,5500,6000,6,0,1
29,356,170,5,0,100M,235,pi,1048576,2,1,...,235,hey,1,2,1,7500,8000,7,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53271,219606,163,5,0,100M,235,cond_mod,68630377364883,2,1,...,235,cond_mod,68630377364883,2,1,7500,8000,4,0,0
53272,219607,16,1,0,100M,235,cond_mod,7625597484987,2,1,...,235,hey,1,2,1,1500,2000,7,0,0
53273,219608,12,5,0,100M,235,hey,1,2,1,...,235,cond_mod,847288609443,2,1,7500,8000,5,0,0
53274,219609,65,3,0,100M,235,hey,1,2,1,...,235,cond_mod,22876792454961,2,1,6500,7000,6,0,0
53275,219610,112,2,0,100M,235,tumatmul,262144,2,1,...,235,hey,1,2,1,1500,2000,1,0,0
53276,219611,161,2,0,100M,235,cond_mod,847288609443,2,1,...,235,tumatmul,65536,2,1,2500,3000,6,0,0
53277,219612,281,3,0,100M,235,pi,65536,2,1,...,235,tumatmul,262144,2,1,4500,5000,4,0,0
53278,219613,75,1,0,100M,235,cond_mod,68630377364883,2,1,...,235,pi,2097152,2,1,2500,3000,7,0,0
53279,219614,192,5,0,100M,235,tumatmul,262144,2,1,...,235,cond_mod,22876792454961,2,1,6500,7000,1,0,0
53280,219615,100,2,0,100M,235,pi,131072,2,1,...,235,tumatmul,131072,2,1,7500,8000,5,0,0
53281,219616,151,4,0,100M,235,tumatmul,524288,2,1,...,235,hey,1,2,1,500,1000,3,0,0
53282,219617,127,4,0,100M,235,cond_mod,22876792454961,2,1,...,235,tumatmul,4096,2,1,500,1000,4,0,0
53283,219618,7,1,0,100M,235,pi,16384,2,1,...,235,cond_mod,847288609443,2,1,3500,4000,7,0,0
53284,219619,127,4,0,100M,235,cond_mod,22876792454961,2,1,...,235,hey,1,2,1,500,1000,1,0,0
53285,219620,60,1,0,100M,235,cond_mod,68630377364883,2,1,...,235,cond_mod,22876792454961,2,1,7500,8000,7,0,0
53286,219621,97,3,0,100M,235,pi,2097152,2,1,...,235,pi,2097152,2,1,2500,3000,5,0,0
53287,219622,6,2,0,100M,235,tumatmul,262144,2,1,...,235,hey,1,2,1,1500,2000,7,0,0
53288,219623,195,4,0,100M,235,pi,131072,2,1,...,235,tumatmul,262144,2,1,1500,2000,3,0,0
53289,219624,188,1,0,100M,235,tumatmul,262144,2,1,...,235,cond_mod,7625597484987,2,1,7500,8000,5,0,0
53290,219625,75,1,0,100M,235,cond_mod,68630377364883,2,1,...,235,hey,1,2,1,2500,3000,3,0,0
53291,219626,19,5,0,100M,235,tumatmul,4096,2,1,...,235,tumatmul,131072,2,1,7500,8000,5,0,0
53292,219627,19,5,0,100M,235,tumatmul,4096,2,1,...,235,cond_mod,22876792454961,2,1,6500,7000,7,0,0
53293,219628,127,4,0,100M,235,cond_mod,22876792454961,2,1,...,235,tumatmul,32768,2,1,3500,4000,5,0,0
53294,219629,79,3,0,100M,235,pi,2097152,2,1,...,235,tumatmul,8192,2,1,1500,2000,1,0,0
53295,219630,37,2,0,100M,235,pi,524288,2,1,...,235,hey,1,2,1,500,1000,3,0,0
53296,219631,112,2,0,100M,235,tumatmul,262144,2,1,...,235,cond_mod,68630377364883,2,1,4500,5000,7,0,0
53297,219632,13,3,0,100M,235,cond_mod,7625597484987,2,1,...,235,cond_mod,22876792454961,2,1,7500,8000,7,0,0
53298,219633,6,2,0,100M,235,tumatmul,262144,2,1,...,235,tumatmul,262144,2,1,7500,8000,6,0,0
53299,219634,95,5,0,100M,235,tumatmul,16384,2,1,...,235,cond_mod,22876792454961,2,1,6500,7000,1,0,0
53300,219635,41,3,0,100M,235,pi,1048576,2,1,...,235,cond_mod,22876792454961,2,1,6500,7000,1,0,0

In [16]:
ID + CONSTANT_VALS

['Set_ID',
 'Task_ID',
 'Deadline',
 'Quota',
 'CAPS',
 'PKG',
 'CORES',
 'COREOFFSET',
 'CRITICALTIME',
 'PERIOD']

In [6]:
# We could probably also use PCA for this
ID = ["Set_ID", "Task_ID"]
CONSTANT_VALS = ["Deadline", "Quota", "CAPS", "PKG", "CORES", "COREOFFSET", "OFFSET"]
LABELS = ["Successful"]
raw_df = tkst_df.drop(columns = ID + CONSTANT_VALS)

In [7]:
raw_df

,Priority,Arg,CRITICALTIME,Period,Number_of_Jobs,Priority,Arg,CRITICALTIME,Period,Number_of_Jobs,Successful
0,2,524288,5500,6000,2,2,131072,2500,3000,7,1
1,2,2097152,6500,7000,2,3,1,3500,4000,7,1
2,3,1,6500,7000,3,4,22876792454961,6500,7000,4,1
3,1,131072,2500,3000,3,5,524288,4500,5000,5,1
4,1,32768,4500,5000,6,2,262144,5500,6000,3,1
5,3,262144,1500,2000,1,4,32768,2500,3000,2,1
6,1,8192,6500,7000,4,2,262144,6500,7000,4,1
7,4,68630377364883,5500,6000,1,4,1,7500,8000,7,1
8,2,1,1500,2000,1,4,8192,4500,5000,3,1
9,4,4096,5500,6000,4,5,4096,5500,6000,3,1
10,2,1,5500,6000,5,4,8192,3500,4000,8,1
11,2,1,2500,3000,1,5,1,500,1000,1,1
12,3,1,3500,4000,6,2,8192,5500,6000,5,1
13,3,1,2500,3000,1,3,65536,2500,3000,6,1
14,3,1,6500,7000,3,1,1,7500,8000,3,1
15,1,1,3500,4000,2,1,1,5500,6000,8,1
16,1,16384,3500,4000,2,1,131072,2500,3000,7,1
17,2,262144,6500,7000,4,5,1,2500,3000,7,1
18,4,262144,3500,4000,7,5,16384,3500,4000,7,1
19,5,1,4500,5000,1,2,16384,500,1000,5,1
20,2,847288609443,7500,8000,5,2,1,7500,8000,1,1
21,4,1,5500,6000,2,3,131072,500,1000,2,1
22,3,1,500,1000,3,4,1,1500,2000,2,1
23,2,262144,3500,4000,6,5,847288609443,6500,7000,3,1
24,4,4096,5500,6000,4,1,65536,7500,8000,2,1
25,1,524288,3500,4000,3,5,4096,6500,7000,7,1
26,1,1,3500,4000,7,1,131072,2500,3000,7,1
27,3,68630377364883,5500,6000,8,2,16384,5500,6000,1,1
28,3,2097152,6500,7000,7,1,16384,5500,6000,6,1
29,5,1048576,7500,8000,3,4,1,7500,8000,7,1
...,...,...,...,...,...,...,...,...,...,...,...
53271,5,68630377364883,4500,5000,4,3,68630377364883,7500,8000,4,0
53272,1,7625597484987,7500,8000,8,4,1,1500,2000,7,0
53273,5,1,2500,3000,2,2,847288609443,7500,8000,5,0
53274,3,1,4500,5000,6,2,22876792454961,6500,7000,6,0
53275,2,262144,7500,8000,6,4,1,1500,2000,1,0
53276,2,847288609443,4500,5000,7,3,65536,2500,3000,6,0
53277,3,65536,500,1000,6,1,262144,4500,5000,4,0
53278,1,68630377364883,3500,4000,1,4,2097152,2500,3000,7,0
53279,5,262144,2500,3000,7,4,22876792454961,6500,7000,1,0
53280,2,131072,500,1000,2,2,131072,7500,8000,5,0
53281,4,524288,4500,5000,1,5,1,500,1000,3,0
53282,4,22876792454961,5500,6000,5,1,4096,500,1000,4,0
53283,1,16384,1500,2000,1,1,847288609443,3500,4000,7,0
53284,4,22876792454961,5500,6000,5,5,1,500,1000,1,0
53285,1,68630377364883,7500,8000,2,1,22876792454961,7500,8000,7,0
53286,3,2097152,6500,7000,7,5,2097152,2500,3000,5,0
53287,2,262144,1500,2000,8,4,1,1500,2000,7,0
53288,4,131072,1500,2000,8,2,262144,1500,2000,3,0
53289,1,262144,2500,3000,1,1,7625597484987,7500,8000,5,0
53290,1,68630377364883,3500,4000,1,3,1,2500,3000,3,0
53291,5,4096,500,1000,8,2,131072,7500,8000,5,0
53292,5,4096,500,1000,8,5,22876792454961,6500,7000,7,0
53293,4,22876792454961,5500,6000,5,1,32768,3500,4000,5,0
53294,3,2097152,6500,7000,2,4,8192,1500,2000,1,0
53295,2,524288,5500,6000,2,3,1,500,1000,3,0
53296,2,262144,7500,8000,6,5,68630377364883,4500,5000,7,0
53297,3,7625597484987,7500,8000,5,1,22876792454961,7500,8000,7,0
53298,2,262144,1500,2000,8,2,262144,7500,8000,6,0
53299,5,16384,1500,2000,6,4,22876792454961,6500,7000,1,0
53300,3,1048576,4500,5000,5,4,22876792454961,6500,7000,1,0

In [8]:
import pickle

raw_df.to_pickle('two_sets.pickle')

In [16]:
raw_df['Successful'].values
# training_raw = raw_df
# training_raw.drop(columns = LABELS, axis = 1)
# training_raw
training_raw.drop('Successful', axis = 1)

,Priority,Arg,CRITICALTIME,Period,Number_of_Jobs,Priority,Arg,CRITICALTIME,Period,Number_of_Jobs
0,2,524288,5500,6000,2,2,131072,2500,3000,7
1,2,2097152,6500,7000,2,3,1,3500,4000,7
2,3,1,6500,7000,3,4,22876792454961,6500,7000,4
3,1,131072,2500,3000,3,5,524288,4500,5000,5
4,1,32768,4500,5000,6,2,262144,5500,6000,3
5,3,262144,1500,2000,1,4,32768,2500,3000,2
6,1,8192,6500,7000,4,2,262144,6500,7000,4
7,4,68630377364883,5500,6000,1,4,1,7500,8000,7
8,2,1,1500,2000,1,4,8192,4500,5000,3
9,4,4096,5500,6000,4,5,4096,5500,6000,3
10,2,1,5500,6000,5,4,8192,3500,4000,8
11,2,1,2500,3000,1,5,1,500,1000,1
12,3,1,3500,4000,6,2,8192,5500,6000,5
13,3,1,2500,3000,1,3,65536,2500,3000,6
14,3,1,6500,7000,3,1,1,7500,8000,3
15,1,1,3500,4000,2,1,1,5500,6000,8
16,1,16384,3500,4000,2,1,131072,2500,3000,7
17,2,262144,6500,7000,4,5,1,2500,3000,7
18,4,262144,3500,4000,7,5,16384,3500,4000,7
19,5,1,4500,5000,1,2,16384,500,1000,5
20,2,847288609443,7500,8000,5,2,1,7500,8000,1
21,4,1,5500,6000,2,3,131072,500,1000,2
22,3,1,500,1000,3,4,1,1500,2000,2
23,2,262144,3500,4000,6,5,847288609443,6500,7000,3
24,4,4096,5500,6000,4,1,65536,7500,8000,2
25,1,524288,3500,4000,3,5,4096,6500,7000,7
26,1,1,3500,4000,7,1,131072,2500,3000,7
27,3,68630377364883,5500,6000,8,2,16384,5500,6000,1
28,3,2097152,6500,7000,7,1,16384,5500,6000,6
29,5,1048576,7500,8000,3,4,1,7500,8000,7
...,...,...,...,...,...,...,...,...,...,...
53271,5,68630377364883,4500,5000,4,3,68630377364883,7500,8000,4
53272,1,7625597484987,7500,8000,8,4,1,1500,2000,7
53273,5,1,2500,3000,2,2,847288609443,7500,8000,5
53274,3,1,4500,5000,6,2,22876792454961,6500,7000,6
53275,2,262144,7500,8000,6,4,1,1500,2000,1
53276,2,847288609443,4500,5000,7,3,65536,2500,3000,6
53277,3,65536,500,1000,6,1,262144,4500,5000,4
53278,1,68630377364883,3500,4000,1,4,2097152,2500,3000,7
53279,5,262144,2500,3000,7,4,22876792454961,6500,7000,1
53280,2,131072,500,1000,2,2,131072,7500,8000,5
53281,4,524288,4500,5000,1,5,1,500,1000,3
53282,4,22876792454961,5500,6000,5,1,4096,500,1000,4
53283,1,16384,1500,2000,1,1,847288609443,3500,4000,7
53284,4,22876792454961,5500,6000,5,5,1,500,1000,1
53285,1,68630377364883,7500,8000,2,1,22876792454961,7500,8000,7
53286,3,2097152,6500,7000,7,5,2097152,2500,3000,5
53287,2,262144,1500,2000,8,4,1,1500,2000,7
53288,4,131072,1500,2000,8,2,262144,1500,2000,3
53289,1,262144,2500,3000,1,1,7625597484987,7500,8000,5
53290,1,68630377364883,3500,4000,1,3,1,2500,3000,3
53291,5,4096,500,1000,8,2,131072,7500,8000,5
53292,5,4096,500,1000,8,5,22876792454961,6500,7000,7
53293,4,22876792454961,5500,6000,5,1,32768,3500,4000,5
53294,3,2097152,6500,7000,2,4,8192,1500,2000,1
53295,2,524288,5500,6000,2,3,1,500,1000,3
53296,2,262144,7500,8000,6,5,68630377364883,4500,5000,7
53297,3,7625597484987,7500,8000,5,1,22876792454961,7500,8000,7
53298,2,262144,1500,2000,8,2,262144,7500,8000,6
53299,5,16384,1500,2000,6,4,22876792454961,6500,7000,1
53300,3,1048576,4500,5000,5,4,22876792454961,6500,7000,1

In [94]:
training_raw

# Pytorch tensors
y = torch.tensor(raw_df['Successful'].values)
x = torch.tensor(training_raw.values)
assert(len(x) == len(y))

# Tensorflow tensors

In [98]:
y = x[:,-1]

In [103]:
x[:,:-1]

IndexError: too many indices for tensor of dimension 1

In [50]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Activation
from keras.optimizers import SGD
from keras.layers import Dense
from keras.utils import np_utils

model = Sequential()
model.add(Dense(768, input_dim=x.shape[0], kernel_initializer="uniform",
activation="relu"))
model.add(Dense(384, activation="relu", kernel_initializer="uniform"))
model.add(Dense(2))
model.add(Activation("softmax"))

In [51]:
print("[INFO] compiling model...")
sgd = SGD(lr=0.01)
model.compile(loss="binary_crossentropy", optimizer=sgd,
metrics=["accuracy"])
model.fit(x,y, epochs=1, batch_size=128, verbose=1)

[INFO] compiling model...

AttributeError: 'Tensor' object has no attribute 'ndim'

In [56]:
from keras_pandas import lib
from keras_pandas.Automater import Automater

categorical_vars = ['pclass', 'sex', 'survived']
numerical_vars = ['age', 'siblings_spouses_aboard', 'parents_children_aboard', 'fare']
text_vars = ['Arg', 'CRITICALTIME' ,'Period' ,'Number_of_Jobs', 'OFFSET', 'Priority']

Automater(data_type_dict=data_type_dict, output_var=output_var)

C:\Users\Varun\AppData\Roaming\Python\Python35\site-packages\gensim\utils.py:1212: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")

In [62]:
data_type_dict = {'numerical': ['Arg', 'CRITICALTIME' ,'Period' ,'Number_of_Jobs', 'OFFSET', 'Priority', 'Successful']}

output_var = 'Successful'

auto = Automater(data_type_dict= data_type_dict, output_var=output_var) # response_var='Successful')
x,y = auto.fit_transform(training_raw)

KeyError: 'Arg'